---
title: "Inflammation_over_time"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# install.packages("data.table")
# install.packages("ggplot2")
# install.packages("cowplot")
# install.packages("gplots")
# install.packages("RColorBrewer")

library(data.table)
library(ggplot2)
library(cowplot)
library(gplots)
library(RColorBrewer)
library(knitr)

rm(list=ls())

source("/home/ramhak/Dropbox/PHD/PAPER I/R_v2/Function_directory/RTqPCR_data_output_adjuster.R")
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
#IMPORTING DATA
DT <- fread("inflammation_over_time_dataset.csv")

#Adjusting variables
adjustment_cols <- names(DT[,3:length(DT)])
DT[,3:length(DT)] <- DT[,lapply(.SD,numeric_adjust), .SDcols=adjustment_cols]

#Splitting the sample variable into two
DT <- DT[,`:=`(Day=substr(Sample, 1,regexpr(":",Sample)-1), Technical.Replicate=substr(Sample,regexpr(":",Sample)+1, nchar(Sample)))][]

#Removing house keeping genes and IL& (due to lack of measurement for no-injury control)
DT <- DT[!is.na(Expression) & Target!="IL6R"][,!c("Sample","Ctrl")]

#Defining factor variables & relabeling 
DT[, "Target"] <- factor(DT[,Target], levels=c("Arg1R","IL10A","IL1aR","IL1bC","IL4S", "TGFbC", "TNFA"), labels=c("Arg1", "IL10", "IL1a", "IL1b", "IL4", "TGFb", "TNFa"))

DT[,"Day"] <- factor(DT[,Day], levels=c("d1", "d3", "d7", "d14", "NIC"), labels = c("1", "3", "7", "14", "NIC"))

#Normalization of data to no-injury control
DT <- do.call(rbind,lapply(split(DT, DT[,Target]), function(subset){subset[,Normalized.Expression:=subset[,Expression]/median(subset[Day=="NIC",Expression], na.rm=T)-1]}))
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
#Data subset for statistical analysis
DT_statistics <- DT[Normalized.Expression<15 & Day!="NIC",]
DT_statistics[,"Day"] <- factor(DT_statistics[,Day])

#Testing normality
DT_statistics_normality_p <- data.table(Shapiro.Wilk.P=do.call(rbind,lapply(split(DT_statistics, DT_statistics[,Day]), function(subset){shapiro.test(subset[,Normalized.Expression])$p.value})))

#Testing homogenity of variances
DT_statistics_homogenity_p <- fligner.test(DT_statistics[, Expression], DT_statistics[, Day])$p.value

#One-way ANOVA
ANOVA_p <- format(summary(aov(Expression~Day, data=DT_statistics))[[1]]$`Pr(>F)`[1], scientific = T, digits = 3)

#Tukeys Post Hoc test
Tukey_P <- TukeyHSD(aov(Expression~Day, data=DT_statistics))[[1]][1:6,4]
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
#PLOT 1: TME OVERVIEW

colorpalette_1 <- brewer.pal(11,"RdBu")[c(1:3,8:11)]

inflammation_over_time_plot1 <- ggplot(DT[Normalized.Expression <15 & Day!="NIC"],aes(x=Day, y=Normalized.Expression, color=Target, fill=Target))+
  geom_smooth(aes(group = 1), colour="black", level=0.99, show.legend = FALSE, linetype="dotdash", alpha=0.3)+
  geom_rect(aes(xmin=2.5, xmax=4, ymin=0, ymax=17), alpha=0.01, color="black", fill="white", linetype=2, size=0.6)+
  geom_rect(aes(xmin=1, xmax=2, ymin=0, ymax=6), alpha=0.01, color="black", fill="white", linetype=2, size=0.6)+
  geom_point(position = position_dodge(width=0.6), alpha=0.5, size=3, show.legend = F)+
  geom_boxplot(position = position_dodge(width=0.6), width=0.5, alpha=0.8)+
  
  xlab("Days (post SCI)")+
  ylab("Relative expression (%)")+
  
  scale_color_manual(values=colorpalette_1)+
  scale_fill_manual(values=colorpalette_1)+
  scale_x_discrete(labels=c("1","3","7","14"))+
  scale_y_continuous(breaks=seq(0,22,2))+
  
  theme(legend.position = "bottom", legend.title= element_blank(), legend.justification = "center", axis.title = element_text(face="bold", size=17))+
  guides(colour = guide_legend(nrow = 1))+
  
  annotate("text", x=1.5, y=5, label="Transplantation\nInterval", fontface=2, alpha=1, size=2.8)+
  annotate("text", x=3.25, y=16, label="Inflammatory\nInterval", fontface=2, alpha=1, size=3.5)
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
#Table for mean expression and CI per day 
mean_expression_table <- DT_statistics[,.(Mean=mean(Normalized.Expression, na.rm=T), SD=sd(Normalized.Expression, na.rm=T), N=.N), by=Day][,SEMx1.96:=qnorm(0.975)*SD/sqrt(N)][,`:=`(CI.Lower=Mean-SEMx1.96, CI.Upper=Mean+SEMx1.96)][,!c("SD", "N", "SEMx1.96")][order(Day)]
mean_expression_table <- cbind(mean_expression_table[,1], round(mean_expression_table[,2:4],2))
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
#PLOT 2: Heatmap

#Reshaping data for heatmap creation 
DT_summary <- DT[Normalized.Expression<15 & Day!="NIC",.(Mean.Norm.Expression=mean(Normalized.Expression, na.rm=T)),by=c("Day", "Target")]
DT_summary <- dcast.data.table(DT_summary, Target~Day, value.var = "Mean.Norm.Expression")
heatmap_data_matrix <- data.matrix(round(DT_summary[,2:length(DT_summary)],2))
rownames(heatmap_data_matrix) <- DT_summary[,Target]

#Creation of heatmap
heatmap_plot <- function(heat_map_data){
  heatmap.2(heat_map_data,
            trace="none",
            col=c(brewer.pal(11, "RdBu")[c(1:4)], brewer.pal(11, "RdBu")[c(8:11)]),
            cellnote=heat_map_data,
            notecol="white",
            notecex=1.5,
            density.info="none",
            key=F,
            
            na.color = "grey",
            
            dendrogram="column",
            
            srtCol=0, 
            lhei = c(0.1,0.2),
            lwid= c(0.01,0.2))

}
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# #1. Saving pot over time
# ggsave("inflammation_over_time_plot1.jpg", inflammation_over_time_plot1,width=9, height=6, dpi=1000)

##2. Saving heatmap
# jpeg("inflammation_over_time_plot2.jpg",
#      width=5000,
#      height = 5000,
#      units="px",
#      res=600)
# heatmap_plot(heatmap_data_matrix)
# dev.off()

##3. Exporting table of mean expression per day
#fwrite(mean_expression_table, "mean_expression_table.csv", sep=";")

# #4. Exporting p-values for test of normality, homogenity and ANOVA
# statistics_table_1 <- data.table(t(DT_statistics_normality_p), DT_statistics_homogenity_p, ANOVA_p)
# names(statistics_table_1) <- c("Shapiro P-value (d1)", "Shapiro P-value (d3)", "Shapiro P-value (d7)", "Shapiro P-value (d14)", "Fligner Killeen P", "ANOVA P")
# statistics_table_1 <- statistics_table_1
# fwrite(statistics_table_1, "statistics_table_1.csv", sep=";")

# # #5. Exporting post hoc table
# fwrite(data.table(paste("'",attr(Tukey_P, "names")),format(Tukey_P, scientific = T, digits=2)), "post_hoc_table.csv", sep=";")

# # 6. Exporting mean & CI table
# fwrite(mean_expression_table, "mean_expression_table.csv", sep=";")
```
